[workspace]
members = ["src/libkrun", "src/krun_input", "src/libkrunfw-win", "krun-sys-windows"]
default-members = ["src/libkrun", "src/krun_input"]
exclude = ["examples/gtk_display", "corresponding-source/2692169"]
resolver = "2"

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true

[patch.crates-io]
vm-memory = { path = "third_party/vm-memory" }
