// libkrunfw.dll — Windows companion for libkrun
//
// Bundles a pre-built x86_64 Linux kernel (vmlinux ELF) and exports
// krunfw_get_kernel() so that libkrun can discover and load it automatically
// without the caller needing to call krun_set_kernel().
//
// The kernel binary is embedded at compile time via include_bytes!.  Because
// libkrun's set_kernel_bundle() requires host_addr to be 4096-byte aligned,
// we copy the .rdata bytes into a page-aligned heap allocation once (lazily,
// on first call) and return a pointer into that allocation.

use std::alloc::{alloc, Layout};
use std::ffi::c_char;
use std::sync::OnceLock;

// Kernel load / entry addresses — generated by scripts/extract_kernel.sh
// (or edited manually to match your vmlinux).
include!("../kernel/addrs.rs");

// The kernel ELF image, embedded into the DLL's read-only data section.
// Populated by running `scripts/extract_kernel.sh` on a Linux/macOS host.
static KERNEL_BYTES: &[u8] = include_bytes!("../kernel/vmlinux");

// Stores the pointer to the page-aligned copy as a `usize` so the static is
// Send + Sync without any unsafe impl boilerplate.
static ALIGNED_PTR: OnceLock<usize> = OnceLock::new();

/// Return a pointer to a page-aligned copy of the kernel image.
///
/// The copy is created once and lives for the lifetime of the process.
/// Subsequent calls return the same pointer.
unsafe fn aligned_kernel_ptr() -> *const u8 {
    let ptr = ALIGNED_PTR.get_or_init(|| {
        let layout = Layout::from_size_align(KERNEL_BYTES.len(), 4096)
            .expect("libkrunfw: failed to build allocation layout");
        let ptr = alloc(layout);
        assert!(!ptr.is_null(), "libkrunfw: page-aligned allocation failed");
        std::ptr::copy_nonoverlapping(KERNEL_BYTES.as_ptr(), ptr, KERNEL_BYTES.len());
        ptr as usize
    });
    *ptr as *const u8
}

/// Return metadata and a pointer to the embedded kernel image.
///
/// # Safety
/// All three output pointers must be valid, non-null, and properly aligned for
/// their respective types.  The returned pointer is valid for the lifetime of
/// the process (it points into a static allocation).
///
/// This matches the ABI expected by libkrun's `KrunfwBindings::get_kernel`.
#[no_mangle]
pub unsafe extern "C" fn krunfw_get_kernel(
    guest_addr: *mut u64,
    entry_addr: *mut u64,
    size: *mut usize,
) -> *const c_char {
    *guest_addr = KERNEL_GUEST_ADDR;
    *entry_addr = KERNEL_ENTRY_ADDR;
    *size = KERNEL_BYTES.len();
    aligned_kernel_ptr() as *const c_char
}
