/*
 * extract_kernel.c
 *
 * Load libkrunfw.so, call krunfw_get_kernel(), and write:
 *   - kernel/vmlinux   (raw kernel bytes)
 *   - kernel/addrs.rs  (Rust constants for guest_addr and entry_addr)
 *
 * Build:
 *   gcc -o extract_kernel extract_kernel.c -ldl
 *
 * Usage:
 *   ./extract_kernel <path-to-libkrunfw.so>
 */

#include <dlfcn.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

typedef char *(*krunfw_get_kernel_fn)(uint64_t *, uint64_t *, size_t *);

static int makedirs(const char *path) {
    char tmp[4096];
    strncpy(tmp, path, sizeof(tmp) - 1);
    char *p = strrchr(tmp, '/');
    if (p) {
        *p = '\0';
        /* best-effort mkdir -p */
        char cmd[4200];
        snprintf(cmd, sizeof(cmd), "mkdir -p '%s'", tmp);
        system(cmd);
    }
    return 0;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <path-to-libkrunfw.so>\n", argv[0]);
        return 1;
    }

    const char *lib_path = argv[1];

    void *lib = dlopen(lib_path, RTLD_LAZY);
    if (!lib) {
        fprintf(stderr, "dlopen(%s) failed: %s\n", lib_path, dlerror());
        return 1;
    }

    krunfw_get_kernel_fn get_kernel =
        (krunfw_get_kernel_fn)dlsym(lib, "krunfw_get_kernel");
    if (!get_kernel) {
        fprintf(stderr, "dlsym(krunfw_get_kernel) failed: %s\n", dlerror());
        dlclose(lib);
        return 1;
    }

    uint64_t guest_addr = 0, entry_addr = 0;
    size_t size = 0;
    char *kernel_ptr = get_kernel(&guest_addr, &entry_addr, &size);

    if (!kernel_ptr || size == 0) {
        fprintf(stderr, "krunfw_get_kernel returned null or zero size\n");
        dlclose(lib);
        return 1;
    }

    printf("kernel: guest_addr=0x%lx  entry_addr=0x%lx  size=%zu bytes (%.1f MB)\n",
           (unsigned long)guest_addr, (unsigned long)entry_addr,
           size, (double)size / 1048576.0);

    /* ---- write kernel/vmlinux ---- */
    makedirs("kernel/vmlinux");
    FILE *f = fopen("kernel/vmlinux", "wb");
    if (!f) {
        perror("fopen kernel/vmlinux");
        dlclose(lib);
        return 1;
    }
    if (fwrite(kernel_ptr, 1, size, f) != size) {
        perror("fwrite kernel/vmlinux");
        fclose(f);
        dlclose(lib);
        return 1;
    }
    fclose(f);
    printf("wrote kernel/vmlinux (%zu bytes)\n", size);

    /* ---- write kernel/addrs.rs ---- */
    f = fopen("kernel/addrs.rs", "w");
    if (!f) {
        perror("fopen kernel/addrs.rs");
        dlclose(lib);
        return 1;
    }
    fprintf(f,
        "// Kernel guest physical load address and entry point.\n"
        "//\n"
        "// !! THIS FILE IS AUTO-GENERATED by scripts/extract_kernel.sh !!\n"
        "// !! Do not edit manually — re-run the script to regenerate.   !!\n"
        "//\n"
        "// Extracted from: %s\n"
        "\n"
        "pub const KERNEL_GUEST_ADDR: u64 = 0x%lx;\n"
        "pub const KERNEL_ENTRY_ADDR: u64 = 0x%lx;\n",
        lib_path,
        (unsigned long)guest_addr,
        (unsigned long)entry_addr);
    fclose(f);
    printf("wrote kernel/addrs.rs\n");

    dlclose(lib);
    return 0;
}
