// Kernel guest physical load address and entry point.
//
// !! THIS FILE IS AUTO-GENERATED by scripts/extract_kernel.sh !!
// !! Do not edit manually — re-run the script to regenerate.   !!
//
// Extracted from: /tmp/tmp.vJ4TCGf5R8/lib64/libkrunfw.so.5.2.1

pub const KERNEL_GUEST_ADDR: u64 = 0x1000000;
pub const KERNEL_ENTRY_ADDR: u64 = 0x1000123;
