// Kernel guest physical load address and entry point.
//
// !! THIS FILE IS AUTO-GENERATED by scripts/extract_kernel.sh !!
// !! Do not edit manually — re-run the script to regenerate.   !!
//
// These values are read at runtime from the upstream libkrunfw.so and must
// match the vmlinux ELF stored in kernel/vmlinux.
//
// x86_64 Linux boot protocol: kernel is placed at 16 MB (0x0100_0000) in
// the guest physical address space; the ELF entry point is the same address.

pub const KERNEL_GUEST_ADDR: u64 = 0x0100_0000;
pub const KERNEL_ENTRY_ADDR: u64 = 0x0100_0000;
